trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: unyleya-projeto-cicd-adolfosouza

steps:
- task: DockerInstaller@0
  displayName: 'Instalar Docker'
  inputs:
    dockerVersion: 'latest'

- task: Docker@2
  displayName: 'Login no Docker Hub'
  inputs:
    command: login
    containerRegistry: 'adolfosouza'

- task: Docker@2
  displayName: 'Build da imagem Docker'
  inputs:
    command: build
    Dockerfile: '**/Dockerfile'
    tags: |
      $(imageName):$(Build.BuildId)

- task: Docker@2
  displayName: 'Push da imagem para o Docker Hub'
  inputs:
    command: push
    tags: |
      $(imageName):$(Build.BuildId)
